package Admin;

import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.util.*;
import java.sql.Timestamp;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JPanel;
import com.mysql.jdbc.*;
import java.rmi.AccessException;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Miguel
 */
public class AdminDashBoard extends javax.swing.JFrame {
      

private JPanel contentPane;

    /**
     * Creates new form sample
     */
    ResultSet rs = null;
    Statement statement=null;
    DBConnect con = null;
    
    public AdminDashBoard() throws SQLException {
        initComponents();
        con=new DBConnect();
        statement=con.getConnection().createStatement();
        update_table();
       fillComboBox();
    }
    void update_table() {
        try {
            rs=statement.executeQuery("select concat(first_name, ' ',middle_name, ' ',last_name) as name,"
                    + " address, position, email, gender, birthdate, salary, pay_type from employees where first_name != 'admin' order by created_at desc");
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (SQLException ex) {
            Logger.getLogger(AdminDashBoard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jRadioButtonMenuItem2 = new javax.swing.JRadioButtonMenuItem();
        payType = new javax.swing.ButtonGroup();
        gender = new javax.swing.ButtonGroup();
        employeeTab = new javax.swing.JTabbedPane();
        Employee = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        editEmployee = new javax.swing.JComboBox();
        editBtn = new javax.swing.JButton();
        addEmployee = new javax.swing.JPanel();
        personalDetails = new javax.swing.JPanel();
        firstNameLabel = new javax.swing.JLabel();
        lastNameLabel = new javax.swing.JLabel();
        firstName = new javax.swing.JTextField();
        lastName = new javax.swing.JTextField();
        birthday = new javax.swing.JLabel();
        birthMonth = new javax.swing.JComboBox<String>();
        birthD = new javax.swing.JComboBox<String>();
        birthYear = new javax.swing.JComboBox<String>();
        genderLabel = new javax.swing.JLabel();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();
        middleNameLabel = new javax.swing.JLabel();
        middleName = new javax.swing.JTextField();
        addressLabel = new javax.swing.JLabel();
        address = new javax.swing.JTextField();
        eMailLabel = new javax.swing.JLabel();
        eMail = new javax.swing.JTextField();
        register = new javax.swing.JButton();
        designation = new javax.swing.JPanel();
        jobTitleLabel = new javax.swing.JLabel();
        jobTitle = new javax.swing.JTextField();
        payTypeLabel = new javax.swing.JLabel();
        pay_type = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        salary = new javax.swing.JTextField();
        banner = new javax.swing.JLabel();
        logout = new javax.swing.JButton();

        jCheckBox1.setText("jCheckBox1");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        jRadioButtonMenuItem2.setSelected(true);
        jRadioButtonMenuItem2.setText("jRadioButtonMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        )
        {public boolean isCellEditable(int rowIndex, int colIndex){return true;}}
    );
    jTable1.setSurrendersFocusOnKeystroke(true);
    jScrollPane1.setViewportView(jTable1);

    editEmployee.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            editEmployeeActionPerformed(evt);
        }
    });

    editBtn.setText("Edit ");
    editBtn.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            editBtnActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout EmployeeLayout = new javax.swing.GroupLayout(Employee);
    Employee.setLayout(EmployeeLayout);
    EmployeeLayout.setHorizontalGroup(
        EmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(EmployeeLayout.createSequentialGroup()
            .addGroup(EmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(EmployeeLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(editBtn)
                    .addGap(12, 12, 12))
                .addGroup(EmployeeLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 763, Short.MAX_VALUE)))
            .addContainerGap())
    );
    EmployeeLayout.setVerticalGroup(
        EmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(EmployeeLayout.createSequentialGroup()
            .addGap(27, 27, 27)
            .addGroup(EmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(editEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(editBtn))
            .addGap(18, 18, 18)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
            .addGap(13, 13, 13))
    );

    employeeTab.addTab("Employee", Employee);

    personalDetails.setBorder(javax.swing.BorderFactory.createTitledBorder("Personal Details"));

    firstNameLabel.setText("First Name");

    lastNameLabel.setText("Last Name");

    birthday.setText("Birthday: m/d/y");

    birthMonth.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
    birthMonth.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            birthMonthActionPerformed(evt);
        }
    });

    birthD.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

    birthYear.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1985", "1986", "1987", "1988", "1989", "1190", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000" }));

    genderLabel.setText("Gender");

    male.setText("Male");
    male.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            maleActionPerformed(evt);
        }
    });

    female.setText("Female");

    middleNameLabel.setText("Middle Name");

    addressLabel.setText("Address");

    eMailLabel.setText("eMail");

    javax.swing.GroupLayout personalDetailsLayout = new javax.swing.GroupLayout(personalDetails);
    personalDetails.setLayout(personalDetailsLayout);
    personalDetailsLayout.setHorizontalGroup(
        personalDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(personalDetailsLayout.createSequentialGroup()
            .addGroup(personalDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(firstNameLabel)
                .addComponent(middleNameLabel)
                .addComponent(lastNameLabel)
                .addComponent(birthday)
                .addComponent(addressLabel)
                .addComponent(genderLabel)
                .addComponent(eMailLabel))
            .addGap(36, 36, 36)
            .addGroup(personalDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addGroup(personalDetailsLayout.createSequentialGroup()
                    .addComponent(birthMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(birthD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(birthYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(firstName, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                .addComponent(middleName, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                .addGroup(personalDetailsLayout.createSequentialGroup()
                    .addComponent(male)
                    .addGap(10, 10, 10)
                    .addComponent(female))
                .addComponent(address)
                .addComponent(lastName, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                .addComponent(eMail))
            .addContainerGap(66, Short.MAX_VALUE))
    );
    personalDetailsLayout.setVerticalGroup(
        personalDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(personalDetailsLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(personalDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(firstNameLabel)
                .addComponent(firstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(personalDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(middleNameLabel)
                .addComponent(middleName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(9, 9, 9)
            .addGroup(personalDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lastNameLabel)
                .addComponent(lastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(personalDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(genderLabel)
                .addComponent(male)
                .addComponent(female))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(personalDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(birthday)
                .addComponent(birthMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(birthD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(birthYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(personalDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(addressLabel)
                .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(personalDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(eMailLabel)
                .addComponent(eMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(60, Short.MAX_VALUE))
    );

    register.setText("Register");
    register.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            registerActionPerformed(evt);
        }
    });

    designation.setBorder(javax.swing.BorderFactory.createTitledBorder("Designation"));

    jobTitleLabel.setText("Job Title");

    jobTitle.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jobTitleActionPerformed(evt);
        }
    });

    payTypeLabel.setText("Pay Type");

    pay_type.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Hourly", "BiMonthly", "Monthly" }));

    jLabel1.setText("Salary");

    javax.swing.GroupLayout designationLayout = new javax.swing.GroupLayout(designation);
    designation.setLayout(designationLayout);
    designationLayout.setHorizontalGroup(
        designationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, designationLayout.createSequentialGroup()
            .addGroup(designationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(designationLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jobTitleLabel)
                    .addGap(40, 40, 40))
                .addGroup(designationLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(designationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(payTypeLabel)
                        .addComponent(jLabel1))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(designationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(pay_type, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jobTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                .addComponent(salary))
            .addGap(130, 130, 130))
    );
    designationLayout.setVerticalGroup(
        designationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(designationLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(designationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jobTitleLabel)
                .addComponent(jobTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(designationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1)
                .addComponent(salary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(designationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(payTypeLabel)
                .addComponent(pay_type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(44, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout addEmployeeLayout = new javax.swing.GroupLayout(addEmployee);
    addEmployee.setLayout(addEmployeeLayout);
    addEmployeeLayout.setHorizontalGroup(
        addEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(addEmployeeLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(personalDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(addEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(addEmployeeLayout.createSequentialGroup()
                    .addGap(164, 164, 164)
                    .addComponent(register))
                .addGroup(addEmployeeLayout.createSequentialGroup()
                    .addGap(32, 32, 32)
                    .addComponent(designation, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap(29, Short.MAX_VALUE))
    );
    addEmployeeLayout.setVerticalGroup(
        addEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addEmployeeLayout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(designation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(register)
            .addGap(181, 181, 181))
        .addGroup(addEmployeeLayout.createSequentialGroup()
            .addComponent(personalDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, Short.MAX_VALUE))
    );

    employeeTab.addTab("Add Employee", addEmployee);

    banner.setFont(new java.awt.Font("Monotype Corsiva", 0, 24)); // NOI18N
    banner.setText("Pay MoreKa");

    logout.setText("Logout");
    logout.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            logoutActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(employeeTab)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(banner)
                            .addGap(353, 353, 353))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(logout)
                            .addGap(17, 17, 17)))))
            .addContainerGap())
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGap(16, 16, 16)
            .addComponent(banner)
            .addGap(28, 28, 28)
            .addComponent(logout)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(employeeTab, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(37, Short.MAX_VALUE))
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        dispose();
        AdminLogin logOut = new AdminLogin();
        logOut.setVisible(true);
    }//GEN-LAST:event_logoutActionPerformed

    private void jobTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jobTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jobTitleActionPerformed

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
        // TODO add your handling code here:
        try{
            Registry reg = LocateRegistry.getRegistry("localhost", 1099);
            PayrollServer msgs = (PayrollServer) reg.lookup("pyserver");
            //          addEmployee(String firstname, String middlename, String lastname, String gender, String address,
                //            String email, String jobTitle, String bday, String pay_type)
            if(male.isSelected()){
                String gender = "Male";
                String bday = birthYear.getSelectedItem() + "-" + birthMonth.getSelectedItem() + "-" + birthD.getSelectedItem();
                msgs.addEmployee(firstName.getText(),middleName.getText(), lastName.getText(),gender, address.getText(), eMail.getText(),
                    jobTitle.getText(), bday, pay_type.getSelectedItem().toString(), salary.getText());
            }else{
                String gender = "Female";
                String bday = birthYear.getSelectedItem() + "-" + birthMonth.getSelectedItem() + "-" + birthD.getSelectedItem();
                msgs.addEmployee(firstName.getText(),middleName.getText(), lastName.getText(), gender, address.getText(), eMail.getText(),
                    jobTitle.getText(), bday, pay_type.getSelectedItem().toString(),salary.getText());
            }

        }catch(Exception e){
            e.printStackTrace();
        }
        dispose();
        try{
            AdminDashBoard dash = new AdminDashBoard();
            dash.setVisible(true);
        }catch(Exception e){
            e.printStackTrace();
        }

    }//GEN-LAST:event_registerActionPerformed
    public void fillComboBox(){
        String url = "jdbc:mysql://localhost:3306/payroll";
        String user = "root";
        String password = "";
        Connection myConn = null;
        Statement myStmt = null;
        ResultSet rs = null;
        try{
            myConn = (Connection) DriverManager.getConnection(url, user, password);
            myStmt = myConn.createStatement();
            String query = "SELECT concat(first_name, ' ', middle_name, ' ', last_name) as name FROM employees";
            rs = myStmt.executeQuery(query);
            
            while(rs.next()){
                editEmployee.addItem(rs.getString("name"));
            } 
        }catch (Exception e){
                    e.printStackTrace();
                    }
    }
    private void maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maleActionPerformed

    private void birthMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_birthMonthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_birthMonthActionPerformed

    private void editEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editEmployeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editEmployeeActionPerformed

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editBtnActionPerformed
    
    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try{
                new AdminDashBoard().setVisible(true);                    
                }catch(Exception e){
                    e.printStackTrace();
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Employee;
    private javax.swing.JPanel addEmployee;
    private javax.swing.JTextField address;
    private javax.swing.JLabel addressLabel;
    private javax.swing.JLabel banner;
    private javax.swing.JComboBox<String> birthD;
    private javax.swing.JComboBox<String> birthMonth;
    private javax.swing.JComboBox<String> birthYear;
    private javax.swing.JLabel birthday;
    private javax.swing.JPanel designation;
    private javax.swing.JTextField eMail;
    private javax.swing.JLabel eMailLabel;
    private javax.swing.JButton editBtn;
    private javax.swing.JComboBox editEmployee;
    private javax.swing.JTabbedPane employeeTab;
    private javax.swing.JRadioButton female;
    private javax.swing.JTextField firstName;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.ButtonGroup gender;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jobTitle;
    private javax.swing.JLabel jobTitleLabel;
    private javax.swing.JTextField lastName;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JButton logout;
    private javax.swing.JRadioButton male;
    private javax.swing.JTextField middleName;
    private javax.swing.JLabel middleNameLabel;
    private javax.swing.ButtonGroup payType;
    private javax.swing.JLabel payTypeLabel;
    private javax.swing.JComboBox pay_type;
    private javax.swing.JPanel personalDetails;
    private javax.swing.JButton register;
    private javax.swing.JTextField salary;
    // End of variables declaration//GEN-END:variables

    void setVisisble(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
